# Generated by Django 5.2.6 on 2025-09-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UzWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('pred_segmentation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
