# Generated by Django 5.2.8 on 2025-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_giventext_ot_sifat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmumiyTurkum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('type_is', models.CharField(blank=True, choices=[('1', 'OT'), ('2', 'SIFAT'), ('3', 'SON'), ('4', "FE'L"), ('5', 'RAVISH'), ('6', 'OLMOSH')], max_length=1, null=True)),
            ],
        ),
    ]
