# Generated by Django 5.2.8 on 2025-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='type_of_these',
            field=models.CharField(blank=True, choices=[('1', 'TEXNIK IBORALAR'), ('2', 'MEDITSINA IBORALAR'), ('3', 'FILOLOGIK IBORALAR')], max_length=1, null=True),
        ),
    ]
